version: '3.8'

services:
  my-app:
    image: mysql
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: mrpassword
      MYSQL_DATABASE: mdatabase
      MYSQL_USER: mami
      MYSQL_PASSWORD: mami1234